2025-03-29 14:19:56,956:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:19:56,960:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:19:56,960:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:19:56,960:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:22:19,362:INFO:PyCaret ClassificationExperiment
2025-03-29 14:22:19,375:INFO:Logging name: clf-default-name
2025-03-29 14:22:19,375:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2025-03-29 14:22:19,375:INFO:version 3.2.0
2025-03-29 14:22:19,375:INFO:Initializing setup()
2025-03-29 14:22:19,375:INFO:self.USI: 9a51
2025-03-29 14:22:19,375:INFO:self._variable_keys: {'_available_plots', 'memory', 'fold_groups_param', 'fix_imbalance', 'y_train', 'html_param', 'is_multiclass', 'exp_id', 'target_param', 'USI', 'log_plots_param', 'exp_name_log', 'gpu_n_jobs_param', 'logging_param', '_ml_usecase', 'pipeline', 'data', 'gpu_param', 'y', 'X', 'fold_shuffle_param', 'y_test', 'idx', 'X_train', 'n_jobs_param', 'fold_generator', 'X_test', 'seed'}
2025-03-29 14:22:19,375:INFO:Checking environment
2025-03-29 14:22:19,375:INFO:python_version: 3.8.18
2025-03-29 14:22:19,375:INFO:python_build: ('default', 'Sep 11 2023 13:39:12')
2025-03-29 14:22:19,384:INFO:machine: AMD64
2025-03-29 14:22:19,384:INFO:platform: Windows-10-10.0.26100-SP0
2025-03-29 14:22:19,408:INFO:Memory: svmem(total=8299257856, available=276320256, percent=96.7, used=8022937600, free=276320256)
2025-03-29 14:22:19,420:INFO:Physical Core: 4
2025-03-29 14:22:19,420:INFO:Logical Core: 8
2025-03-29 14:22:19,420:INFO:Checking libraries
2025-03-29 14:22:19,420:INFO:System:
2025-03-29 14:22:19,420:INFO:    python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
2025-03-29 14:22:19,420:INFO:executable: C:\Users\babig\anaconda3\envs\pycaret_light\python.exe
2025-03-29 14:22:19,420:INFO:   machine: Windows-10-10.0.26100-SP0
2025-03-29 14:22:19,420:INFO:PyCaret required dependencies:
2025-03-29 14:22:26,926:INFO:                 pip: 23.3.1
2025-03-29 14:22:26,926:INFO:          setuptools: 68.2.2
2025-03-29 14:22:26,926:INFO:             pycaret: 3.2.0
2025-03-29 14:22:26,926:INFO:             IPython: 8.12.3
2025-03-29 14:22:26,928:INFO:          ipywidgets: 8.1.1
2025-03-29 14:22:26,928:INFO:                tqdm: 4.66.1
2025-03-29 14:22:26,928:INFO:               numpy: 1.24.4
2025-03-29 14:22:26,928:INFO:              pandas: 1.5.3
2025-03-29 14:22:26,928:INFO:              jinja2: 3.1.3
2025-03-29 14:22:26,928:INFO:               scipy: 1.10.1
2025-03-29 14:22:26,928:INFO:              joblib: 1.3.2
2025-03-29 14:22:26,928:INFO:             sklearn: 1.2.2
2025-03-29 14:22:26,928:INFO:                pyod: 1.1.2
2025-03-29 14:22:26,928:INFO:            imblearn: 0.12.0
2025-03-29 14:22:26,928:INFO:   category_encoders: 2.6.3
2025-03-29 14:22:26,928:INFO:            lightgbm: 4.3.0
2025-03-29 14:22:26,928:INFO:               numba: 0.58.1
2025-03-29 14:22:26,928:INFO:            requests: 2.31.0
2025-03-29 14:22:26,928:INFO:          matplotlib: 3.6.0
2025-03-29 14:22:26,928:INFO:          scikitplot: 0.3.7
2025-03-29 14:22:26,928:INFO:         yellowbrick: 1.5
2025-03-29 14:22:26,928:INFO:              plotly: 5.18.0
2025-03-29 14:22:26,928:INFO:    plotly-resampler: Not installed
2025-03-29 14:22:26,928:INFO:             kaleido: 0.2.1
2025-03-29 14:22:26,928:INFO:           schemdraw: 0.15
2025-03-29 14:22:26,928:INFO:         statsmodels: 0.14.1
2025-03-29 14:22:26,928:INFO:              sktime: 0.21.1
2025-03-29 14:22:26,928:INFO:               tbats: 1.1.3
2025-03-29 14:22:26,928:INFO:            pmdarima: 2.0.4
2025-03-29 14:22:26,928:INFO:              psutil: 5.9.8
2025-03-29 14:22:26,928:INFO:          markupsafe: 2.1.4
2025-03-29 14:22:26,928:INFO:             pickle5: Not installed
2025-03-29 14:22:26,928:INFO:         cloudpickle: 2.2.1
2025-03-29 14:22:26,928:INFO:         deprecation: 2.1.0
2025-03-29 14:22:26,928:INFO:              xxhash: 3.4.1
2025-03-29 14:22:26,928:INFO:           wurlitzer: Not installed
2025-03-29 14:22:26,928:INFO:PyCaret optional dependencies:
2025-03-29 14:22:35,504:INFO:                shap: 0.44.1
2025-03-29 14:22:35,504:INFO:           interpret: 0.5.0
2025-03-29 14:22:35,507:INFO:                umap: 0.5.5
2025-03-29 14:22:35,507:INFO:     ydata_profiling: 4.6.0
2025-03-29 14:22:35,507:INFO:  explainerdashboard: 0.4.5
2025-03-29 14:22:35,507:INFO:             autoviz: Not installed
2025-03-29 14:22:35,507:INFO:           fairlearn: 0.7.0
2025-03-29 14:22:35,507:INFO:          deepchecks: Not installed
2025-03-29 14:22:35,507:INFO:             xgboost: 2.0.3
2025-03-29 14:22:35,507:INFO:            catboost: 1.2.2
2025-03-29 14:22:35,507:INFO:              kmodes: 0.12.2
2025-03-29 14:22:35,507:INFO:             mlxtend: 0.23.1
2025-03-29 14:22:35,507:INFO:       statsforecast: 1.5.0
2025-03-29 14:22:35,507:INFO:        tune_sklearn: 0.5.0
2025-03-29 14:22:35,507:INFO:                 ray: 2.9.1
2025-03-29 14:22:35,507:INFO:            hyperopt: 0.2.7
2025-03-29 14:22:35,507:INFO:              optuna: 3.5.0
2025-03-29 14:22:35,507:INFO:               skopt: 0.9.0
2025-03-29 14:22:35,507:INFO:              mlflow: 1.30.1
2025-03-29 14:22:35,509:INFO:              gradio: 3.50.2
2025-03-29 14:22:35,509:INFO:             fastapi: 0.109.0
2025-03-29 14:22:35,509:INFO:             uvicorn: 0.27.0.post1
2025-03-29 14:22:35,509:INFO:              m2cgen: 0.10.0
2025-03-29 14:22:35,509:INFO:           evidently: 0.2.8
2025-03-29 14:22:35,509:INFO:               fugue: 0.8.6
2025-03-29 14:22:35,509:INFO:           streamlit: Not installed
2025-03-29 14:22:35,509:INFO:             prophet: Not installed
2025-03-29 14:22:35,509:INFO:None
2025-03-29 14:22:35,510:INFO:Set up GPU usage.
2025-03-29 14:22:35,510:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:22:35,510:WARNING:cuML is outdated or not found. Required version is >=23.08.
                Please visit https://rapids.ai/install for installation instructions.
2025-03-29 14:22:35,512:INFO:Set up data.
2025-03-29 14:26:15,829:INFO:PyCaret ClassificationExperiment
2025-03-29 14:26:15,832:INFO:Logging name: clf-default-name
2025-03-29 14:26:15,832:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2025-03-29 14:26:15,832:INFO:version 3.2.0
2025-03-29 14:26:15,832:INFO:Initializing setup()
2025-03-29 14:26:15,832:INFO:self.USI: be3d
2025-03-29 14:26:15,832:INFO:self._variable_keys: {'_available_plots', 'memory', 'fold_groups_param', 'fix_imbalance', 'y_train', 'html_param', 'is_multiclass', 'exp_id', 'target_param', 'USI', 'log_plots_param', 'exp_name_log', 'gpu_n_jobs_param', 'logging_param', '_ml_usecase', 'pipeline', 'data', 'gpu_param', 'y', 'X', 'fold_shuffle_param', 'y_test', 'idx', 'X_train', 'n_jobs_param', 'fold_generator', 'X_test', 'seed'}
2025-03-29 14:26:15,832:INFO:Checking environment
2025-03-29 14:26:15,832:INFO:python_version: 3.8.18
2025-03-29 14:26:15,832:INFO:python_build: ('default', 'Sep 11 2023 13:39:12')
2025-03-29 14:26:15,832:INFO:machine: AMD64
2025-03-29 14:26:15,832:INFO:platform: Windows-10-10.0.26100-SP0
2025-03-29 14:26:15,844:INFO:Memory: svmem(total=8299257856, available=745783296, percent=91.0, used=7553474560, free=745783296)
2025-03-29 14:26:15,844:INFO:Physical Core: 4
2025-03-29 14:26:15,844:INFO:Logical Core: 8
2025-03-29 14:26:15,844:INFO:Checking libraries
2025-03-29 14:26:15,844:INFO:System:
2025-03-29 14:26:15,844:INFO:    python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
2025-03-29 14:26:15,844:INFO:executable: C:\Users\babig\anaconda3\envs\pycaret_light\python.exe
2025-03-29 14:26:15,844:INFO:   machine: Windows-10-10.0.26100-SP0
2025-03-29 14:26:15,844:INFO:PyCaret required dependencies:
2025-03-29 14:26:15,844:INFO:                 pip: 23.3.1
2025-03-29 14:26:15,844:INFO:          setuptools: 68.2.2
2025-03-29 14:26:15,844:INFO:             pycaret: 3.2.0
2025-03-29 14:26:15,844:INFO:             IPython: 8.12.3
2025-03-29 14:26:15,844:INFO:          ipywidgets: 8.1.1
2025-03-29 14:26:15,844:INFO:                tqdm: 4.66.1
2025-03-29 14:26:15,844:INFO:               numpy: 1.24.4
2025-03-29 14:26:15,844:INFO:              pandas: 1.5.3
2025-03-29 14:26:15,844:INFO:              jinja2: 3.1.3
2025-03-29 14:26:15,844:INFO:               scipy: 1.10.1
2025-03-29 14:26:15,844:INFO:              joblib: 1.3.2
2025-03-29 14:26:15,844:INFO:             sklearn: 1.2.2
2025-03-29 14:26:15,844:INFO:                pyod: 1.1.2
2025-03-29 14:26:15,848:INFO:            imblearn: 0.12.0
2025-03-29 14:26:15,848:INFO:   category_encoders: 2.6.3
2025-03-29 14:26:15,848:INFO:            lightgbm: 4.3.0
2025-03-29 14:26:15,848:INFO:               numba: 0.58.1
2025-03-29 14:26:15,848:INFO:            requests: 2.31.0
2025-03-29 14:26:15,848:INFO:          matplotlib: 3.6.0
2025-03-29 14:26:15,848:INFO:          scikitplot: 0.3.7
2025-03-29 14:26:15,848:INFO:         yellowbrick: 1.5
2025-03-29 14:26:15,848:INFO:              plotly: 5.18.0
2025-03-29 14:26:15,848:INFO:    plotly-resampler: Not installed
2025-03-29 14:26:15,848:INFO:             kaleido: 0.2.1
2025-03-29 14:26:15,849:INFO:           schemdraw: 0.15
2025-03-29 14:26:15,849:INFO:         statsmodels: 0.14.1
2025-03-29 14:26:15,849:INFO:              sktime: 0.21.1
2025-03-29 14:26:15,849:INFO:               tbats: 1.1.3
2025-03-29 14:26:15,849:INFO:            pmdarima: 2.0.4
2025-03-29 14:26:15,849:INFO:              psutil: 5.9.8
2025-03-29 14:26:15,849:INFO:          markupsafe: 2.1.4
2025-03-29 14:26:15,849:INFO:             pickle5: Not installed
2025-03-29 14:26:15,849:INFO:         cloudpickle: 2.2.1
2025-03-29 14:26:15,849:INFO:         deprecation: 2.1.0
2025-03-29 14:26:15,849:INFO:              xxhash: 3.4.1
2025-03-29 14:26:15,849:INFO:           wurlitzer: Not installed
2025-03-29 14:26:15,849:INFO:PyCaret optional dependencies:
2025-03-29 14:26:15,849:INFO:                shap: 0.44.1
2025-03-29 14:26:15,851:INFO:           interpret: 0.5.0
2025-03-29 14:26:15,851:INFO:                umap: 0.5.5
2025-03-29 14:26:15,851:INFO:     ydata_profiling: 4.6.0
2025-03-29 14:26:15,851:INFO:  explainerdashboard: 0.4.5
2025-03-29 14:26:15,851:INFO:             autoviz: Not installed
2025-03-29 14:26:15,851:INFO:           fairlearn: 0.7.0
2025-03-29 14:26:15,851:INFO:          deepchecks: Not installed
2025-03-29 14:26:15,851:INFO:             xgboost: 2.0.3
2025-03-29 14:26:15,851:INFO:            catboost: 1.2.2
2025-03-29 14:26:15,851:INFO:              kmodes: 0.12.2
2025-03-29 14:26:15,851:INFO:             mlxtend: 0.23.1
2025-03-29 14:26:15,852:INFO:       statsforecast: 1.5.0
2025-03-29 14:26:15,852:INFO:        tune_sklearn: 0.5.0
2025-03-29 14:26:15,852:INFO:                 ray: 2.9.1
2025-03-29 14:26:15,852:INFO:            hyperopt: 0.2.7
2025-03-29 14:26:15,852:INFO:              optuna: 3.5.0
2025-03-29 14:26:15,852:INFO:               skopt: 0.9.0
2025-03-29 14:26:15,852:INFO:              mlflow: 1.30.1
2025-03-29 14:26:15,852:INFO:              gradio: 3.50.2
2025-03-29 14:26:15,852:INFO:             fastapi: 0.109.0
2025-03-29 14:26:15,852:INFO:             uvicorn: 0.27.0.post1
2025-03-29 14:26:15,853:INFO:              m2cgen: 0.10.0
2025-03-29 14:26:15,853:INFO:           evidently: 0.2.8
2025-03-29 14:26:15,853:INFO:               fugue: 0.8.6
2025-03-29 14:26:15,853:INFO:           streamlit: Not installed
2025-03-29 14:26:15,853:INFO:             prophet: Not installed
2025-03-29 14:26:15,853:INFO:None
2025-03-29 14:26:15,853:INFO:Set up GPU usage.
2025-03-29 14:26:15,853:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:26:15,853:WARNING:cuML is outdated or not found. Required version is >=23.08.
                Please visit https://rapids.ai/install for installation instructions.
2025-03-29 14:26:15,853:INFO:Set up data.
2025-03-29 14:31:50,197:INFO:PyCaret ClassificationExperiment
2025-03-29 14:31:50,204:INFO:Logging name: clf-default-name
2025-03-29 14:31:50,204:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2025-03-29 14:31:50,204:INFO:version 3.2.0
2025-03-29 14:31:50,204:INFO:Initializing setup()
2025-03-29 14:31:50,204:INFO:self.USI: 4ae3
2025-03-29 14:31:50,204:INFO:self._variable_keys: {'_available_plots', 'memory', 'fold_groups_param', 'fix_imbalance', 'y_train', 'html_param', 'is_multiclass', 'exp_id', 'target_param', 'USI', 'log_plots_param', 'exp_name_log', 'gpu_n_jobs_param', 'logging_param', '_ml_usecase', 'pipeline', 'data', 'gpu_param', 'y', 'X', 'fold_shuffle_param', 'y_test', 'idx', 'X_train', 'n_jobs_param', 'fold_generator', 'X_test', 'seed'}
2025-03-29 14:31:50,211:INFO:Checking environment
2025-03-29 14:31:50,212:INFO:python_version: 3.8.18
2025-03-29 14:31:50,212:INFO:python_build: ('default', 'Sep 11 2023 13:39:12')
2025-03-29 14:31:50,212:INFO:machine: AMD64
2025-03-29 14:31:50,212:INFO:platform: Windows-10-10.0.26100-SP0
2025-03-29 14:31:50,230:INFO:Memory: svmem(total=8299257856, available=336519168, percent=95.9, used=7962738688, free=336519168)
2025-03-29 14:31:50,230:INFO:Physical Core: 4
2025-03-29 14:31:50,230:INFO:Logical Core: 8
2025-03-29 14:31:50,230:INFO:Checking libraries
2025-03-29 14:31:50,230:INFO:System:
2025-03-29 14:31:50,230:INFO:    python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
2025-03-29 14:31:50,230:INFO:executable: C:\Users\babig\anaconda3\envs\pycaret_light\python.exe
2025-03-29 14:31:50,230:INFO:   machine: Windows-10-10.0.26100-SP0
2025-03-29 14:31:50,230:INFO:PyCaret required dependencies:
2025-03-29 14:31:50,245:INFO:                 pip: 23.3.1
2025-03-29 14:31:50,245:INFO:          setuptools: 68.2.2
2025-03-29 14:31:50,245:INFO:             pycaret: 3.2.0
2025-03-29 14:31:50,245:INFO:             IPython: 8.12.3
2025-03-29 14:31:50,245:INFO:          ipywidgets: 8.1.1
2025-03-29 14:31:50,245:INFO:                tqdm: 4.66.1
2025-03-29 14:31:50,245:INFO:               numpy: 1.24.4
2025-03-29 14:31:50,245:INFO:              pandas: 1.5.3
2025-03-29 14:31:50,245:INFO:              jinja2: 3.1.3
2025-03-29 14:31:50,245:INFO:               scipy: 1.10.1
2025-03-29 14:31:50,245:INFO:              joblib: 1.3.2
2025-03-29 14:31:50,245:INFO:             sklearn: 1.2.2
2025-03-29 14:31:50,245:INFO:                pyod: 1.1.2
2025-03-29 14:31:50,245:INFO:            imblearn: 0.12.0
2025-03-29 14:31:50,245:INFO:   category_encoders: 2.6.3
2025-03-29 14:31:50,245:INFO:            lightgbm: 4.3.0
2025-03-29 14:31:50,245:INFO:               numba: 0.58.1
2025-03-29 14:31:50,245:INFO:            requests: 2.31.0
2025-03-29 14:31:50,245:INFO:          matplotlib: 3.6.0
2025-03-29 14:31:50,245:INFO:          scikitplot: 0.3.7
2025-03-29 14:31:50,245:INFO:         yellowbrick: 1.5
2025-03-29 14:31:50,245:INFO:              plotly: 5.18.0
2025-03-29 14:31:50,245:INFO:    plotly-resampler: Not installed
2025-03-29 14:31:50,245:INFO:             kaleido: 0.2.1
2025-03-29 14:31:50,245:INFO:           schemdraw: 0.15
2025-03-29 14:31:50,253:INFO:         statsmodels: 0.14.1
2025-03-29 14:31:50,253:INFO:              sktime: 0.21.1
2025-03-29 14:31:50,253:INFO:               tbats: 1.1.3
2025-03-29 14:31:50,253:INFO:            pmdarima: 2.0.4
2025-03-29 14:31:50,255:INFO:              psutil: 5.9.8
2025-03-29 14:31:50,256:INFO:          markupsafe: 2.1.4
2025-03-29 14:31:50,256:INFO:             pickle5: Not installed
2025-03-29 14:31:50,256:INFO:         cloudpickle: 2.2.1
2025-03-29 14:31:50,256:INFO:         deprecation: 2.1.0
2025-03-29 14:31:50,256:INFO:              xxhash: 3.4.1
2025-03-29 14:31:50,256:INFO:           wurlitzer: Not installed
2025-03-29 14:31:50,256:INFO:PyCaret optional dependencies:
2025-03-29 14:31:50,260:INFO:                shap: 0.44.1
2025-03-29 14:31:50,260:INFO:           interpret: 0.5.0
2025-03-29 14:31:50,260:INFO:                umap: 0.5.5
2025-03-29 14:31:50,260:INFO:     ydata_profiling: 4.6.0
2025-03-29 14:31:50,260:INFO:  explainerdashboard: 0.4.5
2025-03-29 14:31:50,260:INFO:             autoviz: Not installed
2025-03-29 14:31:50,262:INFO:           fairlearn: 0.7.0
2025-03-29 14:31:50,262:INFO:          deepchecks: Not installed
2025-03-29 14:31:50,262:INFO:             xgboost: 2.0.3
2025-03-29 14:31:50,262:INFO:            catboost: 1.2.2
2025-03-29 14:31:50,262:INFO:              kmodes: 0.12.2
2025-03-29 14:31:50,262:INFO:             mlxtend: 0.23.1
2025-03-29 14:31:50,262:INFO:       statsforecast: 1.5.0
2025-03-29 14:31:50,262:INFO:        tune_sklearn: 0.5.0
2025-03-29 14:31:50,262:INFO:                 ray: 2.9.1
2025-03-29 14:31:50,262:INFO:            hyperopt: 0.2.7
2025-03-29 14:31:50,262:INFO:              optuna: 3.5.0
2025-03-29 14:31:50,262:INFO:               skopt: 0.9.0
2025-03-29 14:31:50,262:INFO:              mlflow: 1.30.1
2025-03-29 14:31:50,262:INFO:              gradio: 3.50.2
2025-03-29 14:31:50,262:INFO:             fastapi: 0.109.0
2025-03-29 14:31:50,262:INFO:             uvicorn: 0.27.0.post1
2025-03-29 14:31:50,262:INFO:              m2cgen: 0.10.0
2025-03-29 14:31:50,262:INFO:           evidently: 0.2.8
2025-03-29 14:31:50,262:INFO:               fugue: 0.8.6
2025-03-29 14:31:50,262:INFO:           streamlit: Not installed
2025-03-29 14:31:50,262:INFO:             prophet: Not installed
2025-03-29 14:31:50,262:INFO:None
2025-03-29 14:31:50,262:INFO:Set up GPU usage.
2025-03-29 14:31:50,264:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:31:50,264:WARNING:cuML is outdated or not found. Required version is >=23.08.
                Please visit https://rapids.ai/install for installation instructions.
2025-03-29 14:31:50,264:INFO:Set up data.
2025-03-29 14:37:56,464:INFO:PyCaret ClassificationExperiment
2025-03-29 14:37:56,472:INFO:Logging name: clf-default-name
2025-03-29 14:37:56,473:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2025-03-29 14:37:56,473:INFO:version 3.2.0
2025-03-29 14:37:56,473:INFO:Initializing setup()
2025-03-29 14:37:56,473:INFO:self.USI: 65af
2025-03-29 14:37:56,473:INFO:self._variable_keys: {'_available_plots', 'memory', 'fold_groups_param', 'fix_imbalance', 'y_train', 'html_param', 'is_multiclass', 'exp_id', 'target_param', 'USI', 'log_plots_param', 'exp_name_log', 'gpu_n_jobs_param', 'logging_param', '_ml_usecase', 'pipeline', 'data', 'gpu_param', 'y', 'X', 'fold_shuffle_param', 'y_test', 'idx', 'X_train', 'n_jobs_param', 'fold_generator', 'X_test', 'seed'}
2025-03-29 14:37:56,473:INFO:Checking environment
2025-03-29 14:37:56,473:INFO:python_version: 3.8.18
2025-03-29 14:37:56,473:INFO:python_build: ('default', 'Sep 11 2023 13:39:12')
2025-03-29 14:37:56,480:INFO:machine: AMD64
2025-03-29 14:37:56,480:INFO:platform: Windows-10-10.0.26100-SP0
2025-03-29 14:37:56,497:INFO:Memory: svmem(total=8299257856, available=694910976, percent=91.6, used=7604346880, free=694910976)
2025-03-29 14:37:56,497:INFO:Physical Core: 4
2025-03-29 14:37:56,497:INFO:Logical Core: 8
2025-03-29 14:37:56,497:INFO:Checking libraries
2025-03-29 14:37:56,497:INFO:System:
2025-03-29 14:37:56,497:INFO:    python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
2025-03-29 14:37:56,503:INFO:executable: C:\Users\babig\anaconda3\envs\pycaret_light\python.exe
2025-03-29 14:37:56,504:INFO:   machine: Windows-10-10.0.26100-SP0
2025-03-29 14:37:56,504:INFO:PyCaret required dependencies:
2025-03-29 14:37:56,512:INFO:                 pip: 23.3.1
2025-03-29 14:37:56,512:INFO:          setuptools: 68.2.2
2025-03-29 14:37:56,512:INFO:             pycaret: 3.2.0
2025-03-29 14:37:56,513:INFO:             IPython: 8.12.3
2025-03-29 14:37:56,513:INFO:          ipywidgets: 8.1.1
2025-03-29 14:37:56,513:INFO:                tqdm: 4.66.1
2025-03-29 14:37:56,514:INFO:               numpy: 1.24.4
2025-03-29 14:37:56,514:INFO:              pandas: 1.5.3
2025-03-29 14:37:56,514:INFO:              jinja2: 3.1.3
2025-03-29 14:37:56,514:INFO:               scipy: 1.10.1
2025-03-29 14:37:56,514:INFO:              joblib: 1.3.2
2025-03-29 14:37:56,514:INFO:             sklearn: 1.2.2
2025-03-29 14:37:56,514:INFO:                pyod: 1.1.2
2025-03-29 14:37:56,514:INFO:            imblearn: 0.12.0
2025-03-29 14:37:56,514:INFO:   category_encoders: 2.6.3
2025-03-29 14:37:56,514:INFO:            lightgbm: 4.3.0
2025-03-29 14:37:56,514:INFO:               numba: 0.58.1
2025-03-29 14:37:56,514:INFO:            requests: 2.31.0
2025-03-29 14:37:56,514:INFO:          matplotlib: 3.6.0
2025-03-29 14:37:56,514:INFO:          scikitplot: 0.3.7
2025-03-29 14:37:56,514:INFO:         yellowbrick: 1.5
2025-03-29 14:37:56,515:INFO:              plotly: 5.18.0
2025-03-29 14:37:56,515:INFO:    plotly-resampler: Not installed
2025-03-29 14:37:56,515:INFO:             kaleido: 0.2.1
2025-03-29 14:37:56,515:INFO:           schemdraw: 0.15
2025-03-29 14:37:56,515:INFO:         statsmodels: 0.14.1
2025-03-29 14:37:56,515:INFO:              sktime: 0.21.1
2025-03-29 14:37:56,515:INFO:               tbats: 1.1.3
2025-03-29 14:37:56,515:INFO:            pmdarima: 2.0.4
2025-03-29 14:37:56,515:INFO:              psutil: 5.9.8
2025-03-29 14:37:56,515:INFO:          markupsafe: 2.1.4
2025-03-29 14:37:56,515:INFO:             pickle5: Not installed
2025-03-29 14:37:56,515:INFO:         cloudpickle: 2.2.1
2025-03-29 14:37:56,516:INFO:         deprecation: 2.1.0
2025-03-29 14:37:56,517:INFO:              xxhash: 3.4.1
2025-03-29 14:37:56,517:INFO:           wurlitzer: Not installed
2025-03-29 14:37:56,517:INFO:PyCaret optional dependencies:
2025-03-29 14:37:56,517:INFO:                shap: 0.44.1
2025-03-29 14:37:56,517:INFO:           interpret: 0.5.0
2025-03-29 14:37:56,517:INFO:                umap: 0.5.5
2025-03-29 14:37:56,517:INFO:     ydata_profiling: 4.6.0
2025-03-29 14:37:56,517:INFO:  explainerdashboard: 0.4.5
2025-03-29 14:37:56,517:INFO:             autoviz: Not installed
2025-03-29 14:37:56,517:INFO:           fairlearn: 0.7.0
2025-03-29 14:37:56,517:INFO:          deepchecks: Not installed
2025-03-29 14:37:56,517:INFO:             xgboost: 2.0.3
2025-03-29 14:37:56,517:INFO:            catboost: 1.2.2
2025-03-29 14:37:56,517:INFO:              kmodes: 0.12.2
2025-03-29 14:37:56,517:INFO:             mlxtend: 0.23.1
2025-03-29 14:37:56,517:INFO:       statsforecast: 1.5.0
2025-03-29 14:37:56,517:INFO:        tune_sklearn: 0.5.0
2025-03-29 14:37:56,517:INFO:                 ray: 2.9.1
2025-03-29 14:37:56,517:INFO:            hyperopt: 0.2.7
2025-03-29 14:37:56,517:INFO:              optuna: 3.5.0
2025-03-29 14:37:56,517:INFO:               skopt: 0.9.0
2025-03-29 14:37:56,517:INFO:              mlflow: 1.30.1
2025-03-29 14:37:56,517:INFO:              gradio: 3.50.2
2025-03-29 14:37:56,517:INFO:             fastapi: 0.109.0
2025-03-29 14:37:56,517:INFO:             uvicorn: 0.27.0.post1
2025-03-29 14:37:56,517:INFO:              m2cgen: 0.10.0
2025-03-29 14:37:56,517:INFO:           evidently: 0.2.8
2025-03-29 14:37:56,517:INFO:               fugue: 0.8.6
2025-03-29 14:37:56,517:INFO:           streamlit: Not installed
2025-03-29 14:37:56,517:INFO:             prophet: Not installed
2025-03-29 14:37:56,517:INFO:None
2025-03-29 14:37:56,517:INFO:Set up GPU usage.
2025-03-29 14:37:56,517:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:37:56,517:WARNING:cuML is outdated or not found. Required version is >=23.08.
                Please visit https://rapids.ai/install for installation instructions.
2025-03-29 14:37:56,523:INFO:Set up data.
2025-03-29 14:38:09,946:INFO:Set up folding strategy.
2025-03-29 14:38:09,950:INFO:Set up train/test split.
2025-03-29 14:38:10,622:INFO:Set up index.
2025-03-29 14:38:10,643:INFO:Assigning column types.
2025-03-29 14:38:11,141:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2025-03-29 14:38:11,143:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:11,213:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-03-29 14:38:11,213:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:11,293:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:11,293:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-03-29 14:38:11,293:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:11,462:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:11,481:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:11,512:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 14:38:35,839:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 14:38:36,697:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:36,864:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-03-29 14:38:36,864:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:36,864:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:36,876:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-03-29 14:38:36,876:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:36,958:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:36,976:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:36,979:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 14:38:37,184:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 14:38:37,184:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2025-03-29 14:38:37,191:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,368:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,368:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,374:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-03-29 14:38:37,374:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,453:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,458:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,458:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 14:38:37,524:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 14:38:37,528:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,711:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,713:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,713:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-03-29 14:38:37,713:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,829:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,850:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:37,854:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 14:38:37,929:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 14:38:37,976:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2025-03-29 14:38:37,978:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:38,413:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:38,414:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:38,420:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:38,554:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:38,576:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:38,581:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 14:38:38,776:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 14:38:38,783:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:38,974:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:38,976:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:38,979:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:39,116:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:39,132:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:38:39,138:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 14:38:39,283:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 14:38:39,310:INFO:Preparing preprocessing pipeline...
2025-03-29 14:38:39,754:INFO:Set up simple imputation.
2025-03-29 14:38:49,459:INFO:Finished creating preprocessing pipeline.
2025-03-29 14:38:50,016:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\babig\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Basic_Demos_Enroll_Year',
                                             'Basic_Demos_Study_Site',
                                             'PreInt_Demos_Fam_Child_Ethnicity',
                                             'PreInt_Demos_Fam_Child_Race',
                                             'MRI_Track_Scan_Location',
                                             'Barratt_Barratt_P1_Edu',
                                             'Barratt_Barratt_P1_Occ',
                                             'Barratt_Ba...
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False)
2025-03-29 14:38:50,016:INFO:Creating final display dataframe.
2025-03-29 14:39:06,517:INFO:Setup _display_container:                     Description             Value
0                    Session id                42
1                        Target             Sex_F
2                   Target type            Binary
3           Original data shape      (970, 19929)
4        Transformed data shape      (970, 19929)
5   Transformed train set shape      (679, 19929)
6    Transformed test set shape      (291, 19929)
7              Numeric features             19928
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                 5
14                     CPU Jobs                -1
15                      Use GPU              True
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              65af
2025-03-29 14:39:06,644:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,708:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,711:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,711:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,730:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,744:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,744:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 14:39:06,815:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 14:39:06,820:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,888:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,890:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,890:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,915:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,927:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 14:39:06,933:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 14:39:06,957:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 14:39:06,964:INFO:setup() successfully completed in 70.62s...............
2025-03-29 14:39:19,016:INFO:Initializing compare_models()
2025-03-29 14:39:19,016:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2025-03-29 14:39:19,016:INFO:Checking exceptions
2025-03-29 14:39:19,312:INFO:Preparing display monitor
2025-03-29 14:39:19,475:INFO:Initializing Logistic Regression
2025-03-29 14:39:19,475:INFO:Total runtime is 0.00047984917958577476 minutes
2025-03-29 14:39:19,485:INFO:SubProcess create_model() called ==================================
2025-03-29 14:39:19,492:INFO:Initializing create_model()
2025-03-29 14:39:19,492:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:39:19,492:INFO:Checking exceptions
2025-03-29 14:39:19,492:INFO:Importing libraries
2025-03-29 14:39:19,494:INFO:Copying training dataset
2025-03-29 14:39:19,980:INFO:Defining folds
2025-03-29 14:39:19,980:INFO:Declaring metric variables
2025-03-29 14:39:19,988:INFO:Importing untrained model
2025-03-29 14:39:19,999:INFO:Logistic Regression Imported successfully
2025-03-29 14:39:20,018:INFO:Starting cross validation
2025-03-29 14:39:20,117:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 14:41:32,546:INFO:Calculating mean and std
2025-03-29 14:41:32,610:INFO:Creating metrics dataframe
2025-03-29 14:41:32,664:INFO:Uploading results into container
2025-03-29 14:41:32,669:INFO:Uploading model into container now
2025-03-29 14:41:32,674:INFO:_master_model_container: 1
2025-03-29 14:41:32,674:INFO:_display_container: 2
2025-03-29 14:41:32,674:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2025-03-29 14:41:32,674:INFO:create_model() successfully completed......................................
2025-03-29 14:41:36,470:INFO:SubProcess create_model() end ==================================
2025-03-29 14:41:36,478:INFO:Creating metrics dataframe
2025-03-29 14:41:36,517:INFO:Initializing K Neighbors Classifier
2025-03-29 14:41:36,517:INFO:Total runtime is 2.284514876206716 minutes
2025-03-29 14:41:36,528:INFO:SubProcess create_model() called ==================================
2025-03-29 14:41:36,528:INFO:Initializing create_model()
2025-03-29 14:41:36,528:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:41:36,530:INFO:Checking exceptions
2025-03-29 14:41:36,530:INFO:Importing libraries
2025-03-29 14:41:36,532:INFO:Copying training dataset
2025-03-29 14:41:37,351:INFO:Defining folds
2025-03-29 14:41:37,354:INFO:Declaring metric variables
2025-03-29 14:41:37,354:INFO:Importing untrained model
2025-03-29 14:41:37,365:INFO:K Neighbors Classifier Imported successfully
2025-03-29 14:41:37,379:INFO:Starting cross validation
2025-03-29 14:41:37,454:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 14:41:50,003:INFO:Calculating mean and std
2025-03-29 14:41:50,019:INFO:Creating metrics dataframe
2025-03-29 14:41:50,029:INFO:Uploading results into container
2025-03-29 14:41:50,033:INFO:Uploading model into container now
2025-03-29 14:41:50,036:INFO:_master_model_container: 2
2025-03-29 14:41:50,036:INFO:_display_container: 2
2025-03-29 14:41:50,036:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2025-03-29 14:41:50,038:INFO:create_model() successfully completed......................................
2025-03-29 14:41:51,007:INFO:SubProcess create_model() end ==================================
2025-03-29 14:41:51,007:INFO:Creating metrics dataframe
2025-03-29 14:41:51,044:INFO:Initializing Naive Bayes
2025-03-29 14:41:51,044:INFO:Total runtime is 2.5266332109769185 minutes
2025-03-29 14:41:51,049:INFO:SubProcess create_model() called ==================================
2025-03-29 14:41:51,049:INFO:Initializing create_model()
2025-03-29 14:41:51,049:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:41:51,049:INFO:Checking exceptions
2025-03-29 14:41:51,049:INFO:Importing libraries
2025-03-29 14:41:51,050:INFO:Copying training dataset
2025-03-29 14:41:51,401:INFO:Defining folds
2025-03-29 14:41:51,401:INFO:Declaring metric variables
2025-03-29 14:41:51,413:INFO:Importing untrained model
2025-03-29 14:41:51,413:INFO:Naive Bayes Imported successfully
2025-03-29 14:41:51,413:INFO:Starting cross validation
2025-03-29 14:41:51,504:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 14:42:01,291:INFO:Calculating mean and std
2025-03-29 14:42:01,302:INFO:Creating metrics dataframe
2025-03-29 14:42:01,304:INFO:Uploading results into container
2025-03-29 14:42:01,304:INFO:Uploading model into container now
2025-03-29 14:42:01,304:INFO:_master_model_container: 3
2025-03-29 14:42:01,304:INFO:_display_container: 2
2025-03-29 14:42:01,304:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2025-03-29 14:42:01,304:INFO:create_model() successfully completed......................................
2025-03-29 14:42:01,849:INFO:SubProcess create_model() end ==================================
2025-03-29 14:42:01,849:INFO:Creating metrics dataframe
2025-03-29 14:42:01,864:INFO:Initializing Decision Tree Classifier
2025-03-29 14:42:01,864:INFO:Total runtime is 2.7069650371869405 minutes
2025-03-29 14:42:01,864:INFO:SubProcess create_model() called ==================================
2025-03-29 14:42:01,864:INFO:Initializing create_model()
2025-03-29 14:42:01,864:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:42:01,864:INFO:Checking exceptions
2025-03-29 14:42:01,864:INFO:Importing libraries
2025-03-29 14:42:01,864:INFO:Copying training dataset
2025-03-29 14:42:02,175:INFO:Defining folds
2025-03-29 14:42:02,175:INFO:Declaring metric variables
2025-03-29 14:42:02,180:INFO:Importing untrained model
2025-03-29 14:42:02,187:INFO:Decision Tree Classifier Imported successfully
2025-03-29 14:42:02,196:INFO:Starting cross validation
2025-03-29 14:42:02,258:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 14:42:53,896:INFO:Calculating mean and std
2025-03-29 14:42:53,905:INFO:Creating metrics dataframe
2025-03-29 14:42:53,914:INFO:Uploading results into container
2025-03-29 14:42:53,916:INFO:Uploading model into container now
2025-03-29 14:42:53,916:INFO:_master_model_container: 4
2025-03-29 14:42:53,916:INFO:_display_container: 2
2025-03-29 14:42:53,918:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=42, splitter='best')
2025-03-29 14:42:53,918:INFO:create_model() successfully completed......................................
2025-03-29 14:42:54,626:INFO:SubProcess create_model() end ==================================
2025-03-29 14:42:54,626:INFO:Creating metrics dataframe
2025-03-29 14:42:54,639:INFO:Initializing SVM - Linear Kernel
2025-03-29 14:42:54,639:INFO:Total runtime is 3.586549671490987 minutes
2025-03-29 14:42:54,645:INFO:SubProcess create_model() called ==================================
2025-03-29 14:42:54,646:INFO:Initializing create_model()
2025-03-29 14:42:54,646:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:42:54,646:INFO:Checking exceptions
2025-03-29 14:42:54,646:INFO:Importing libraries
2025-03-29 14:42:54,646:INFO:Copying training dataset
2025-03-29 14:42:55,017:INFO:Defining folds
2025-03-29 14:42:55,017:INFO:Declaring metric variables
2025-03-29 14:42:55,017:INFO:Importing untrained model
2025-03-29 14:42:55,027:INFO:SVM - Linear Kernel Imported successfully
2025-03-29 14:42:55,034:INFO:Starting cross validation
2025-03-29 14:42:55,095:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 14:43:09,306:INFO:Calculating mean and std
2025-03-29 14:43:09,308:INFO:Creating metrics dataframe
2025-03-29 14:43:09,316:INFO:Uploading results into container
2025-03-29 14:43:09,316:INFO:Uploading model into container now
2025-03-29 14:43:09,316:INFO:_master_model_container: 5
2025-03-29 14:43:09,316:INFO:_display_container: 2
2025-03-29 14:43:09,316:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2025-03-29 14:43:09,316:INFO:create_model() successfully completed......................................
2025-03-29 14:43:09,992:INFO:SubProcess create_model() end ==================================
2025-03-29 14:43:09,992:INFO:Creating metrics dataframe
2025-03-29 14:43:10,009:INFO:Initializing Ridge Classifier
2025-03-29 14:43:10,010:INFO:Total runtime is 3.842729572455088 minutes
2025-03-29 14:43:10,015:INFO:SubProcess create_model() called ==================================
2025-03-29 14:43:10,016:INFO:Initializing create_model()
2025-03-29 14:43:10,016:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:43:10,016:INFO:Checking exceptions
2025-03-29 14:43:10,016:INFO:Importing libraries
2025-03-29 14:43:10,016:INFO:Copying training dataset
2025-03-29 14:43:10,345:INFO:Defining folds
2025-03-29 14:43:10,345:INFO:Declaring metric variables
2025-03-29 14:43:10,348:INFO:Importing untrained model
2025-03-29 14:43:10,355:INFO:Ridge Classifier Imported successfully
2025-03-29 14:43:10,362:INFO:Starting cross validation
2025-03-29 14:43:10,450:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 14:43:19,297:INFO:Calculating mean and std
2025-03-29 14:43:19,299:INFO:Creating metrics dataframe
2025-03-29 14:43:19,302:INFO:Uploading results into container
2025-03-29 14:43:19,302:INFO:Uploading model into container now
2025-03-29 14:43:19,302:INFO:_master_model_container: 6
2025-03-29 14:43:19,304:INFO:_display_container: 2
2025-03-29 14:43:19,304:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=42, solver='auto',
                tol=0.0001)
2025-03-29 14:43:19,304:INFO:create_model() successfully completed......................................
2025-03-29 14:43:19,843:INFO:SubProcess create_model() end ==================================
2025-03-29 14:43:19,846:INFO:Creating metrics dataframe
2025-03-29 14:43:19,862:INFO:Initializing Random Forest Classifier
2025-03-29 14:43:19,862:INFO:Total runtime is 4.0069329857826235 minutes
2025-03-29 14:43:19,865:INFO:SubProcess create_model() called ==================================
2025-03-29 14:43:19,865:INFO:Initializing create_model()
2025-03-29 14:43:19,865:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:43:19,865:INFO:Checking exceptions
2025-03-29 14:43:19,865:INFO:Importing libraries
2025-03-29 14:43:19,865:INFO:Copying training dataset
2025-03-29 14:43:20,129:INFO:Defining folds
2025-03-29 14:43:20,129:INFO:Declaring metric variables
2025-03-29 14:43:20,129:INFO:Importing untrained model
2025-03-29 14:43:20,142:INFO:Random Forest Classifier Imported successfully
2025-03-29 14:43:20,149:INFO:Starting cross validation
2025-03-29 14:43:20,250:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 14:43:39,836:INFO:Calculating mean and std
2025-03-29 14:43:39,836:INFO:Creating metrics dataframe
2025-03-29 14:43:39,849:INFO:Uploading results into container
2025-03-29 14:43:39,849:INFO:Uploading model into container now
2025-03-29 14:43:39,849:INFO:_master_model_container: 7
2025-03-29 14:43:39,849:INFO:_display_container: 2
2025-03-29 14:43:39,849:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2025-03-29 14:43:39,849:INFO:create_model() successfully completed......................................
2025-03-29 14:43:40,493:INFO:SubProcess create_model() end ==================================
2025-03-29 14:43:40,493:INFO:Creating metrics dataframe
2025-03-29 14:43:40,511:INFO:Initializing Quadratic Discriminant Analysis
2025-03-29 14:43:40,511:INFO:Total runtime is 4.351082146167755 minutes
2025-03-29 14:43:40,511:INFO:SubProcess create_model() called ==================================
2025-03-29 14:43:40,511:INFO:Initializing create_model()
2025-03-29 14:43:40,511:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:43:40,511:INFO:Checking exceptions
2025-03-29 14:43:40,511:INFO:Importing libraries
2025-03-29 14:43:40,511:INFO:Copying training dataset
2025-03-29 14:43:40,809:INFO:Defining folds
2025-03-29 14:43:40,809:INFO:Declaring metric variables
2025-03-29 14:43:40,820:INFO:Importing untrained model
2025-03-29 14:43:40,826:INFO:Quadratic Discriminant Analysis Imported successfully
2025-03-29 14:43:40,836:INFO:Starting cross validation
2025-03-29 14:43:40,901:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 14:44:13,419:INFO:Calculating mean and std
2025-03-29 14:44:13,465:INFO:Creating metrics dataframe
2025-03-29 14:44:13,472:INFO:Uploading results into container
2025-03-29 14:44:13,480:INFO:Uploading model into container now
2025-03-29 14:44:13,486:INFO:_master_model_container: 8
2025-03-29 14:44:13,486:INFO:_display_container: 2
2025-03-29 14:44:13,489:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2025-03-29 14:44:13,489:INFO:create_model() successfully completed......................................
2025-03-29 14:44:14,674:INFO:SubProcess create_model() end ==================================
2025-03-29 14:44:14,675:INFO:Creating metrics dataframe
2025-03-29 14:44:14,702:INFO:Initializing Ada Boost Classifier
2025-03-29 14:44:14,702:INFO:Total runtime is 4.920933401584625 minutes
2025-03-29 14:44:14,710:INFO:SubProcess create_model() called ==================================
2025-03-29 14:44:14,710:INFO:Initializing create_model()
2025-03-29 14:44:14,710:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:44:14,710:INFO:Checking exceptions
2025-03-29 14:44:14,710:INFO:Importing libraries
2025-03-29 14:44:14,714:INFO:Copying training dataset
2025-03-29 14:44:15,225:INFO:Defining folds
2025-03-29 14:44:15,225:INFO:Declaring metric variables
2025-03-29 14:44:15,231:INFO:Importing untrained model
2025-03-29 14:44:15,237:INFO:Ada Boost Classifier Imported successfully
2025-03-29 14:44:15,249:INFO:Starting cross validation
2025-03-29 14:44:15,329:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 14:52:04,076:INFO:Calculating mean and std
2025-03-29 14:52:04,208:INFO:Creating metrics dataframe
2025-03-29 14:52:04,292:INFO:Uploading results into container
2025-03-29 14:52:04,292:INFO:Uploading model into container now
2025-03-29 14:52:04,310:INFO:_master_model_container: 9
2025-03-29 14:52:04,310:INFO:_display_container: 2
2025-03-29 14:52:04,324:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=42)
2025-03-29 14:52:04,324:INFO:create_model() successfully completed......................................
2025-03-29 14:52:09,025:INFO:SubProcess create_model() end ==================================
2025-03-29 14:52:09,025:INFO:Creating metrics dataframe
2025-03-29 14:52:09,063:INFO:Initializing Gradient Boosting Classifier
2025-03-29 14:52:09,063:INFO:Total runtime is 12.826949906349181 minutes
2025-03-29 14:52:09,074:INFO:SubProcess create_model() called ==================================
2025-03-29 14:52:09,074:INFO:Initializing create_model()
2025-03-29 14:52:09,074:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 14:52:09,074:INFO:Checking exceptions
2025-03-29 14:52:09,074:INFO:Importing libraries
2025-03-29 14:52:09,075:INFO:Copying training dataset
2025-03-29 14:52:09,853:INFO:Defining folds
2025-03-29 14:52:09,908:INFO:Declaring metric variables
2025-03-29 14:52:09,914:INFO:Importing untrained model
2025-03-29 14:52:09,925:INFO:Gradient Boosting Classifier Imported successfully
2025-03-29 14:52:09,930:INFO:Starting cross validation
2025-03-29 14:52:10,028:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 15:45:01,458:INFO:Calculating mean and std
2025-03-29 15:45:01,607:INFO:Creating metrics dataframe
2025-03-29 15:45:01,712:INFO:Uploading results into container
2025-03-29 15:45:01,726:INFO:Uploading model into container now
2025-03-29 15:45:01,758:INFO:_master_model_container: 10
2025-03-29 15:45:01,758:INFO:_display_container: 2
2025-03-29 15:45:01,773:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2025-03-29 15:45:01,773:INFO:create_model() successfully completed......................................
2025-03-29 15:45:08,714:INFO:SubProcess create_model() end ==================================
2025-03-29 15:45:08,717:INFO:Creating metrics dataframe
2025-03-29 15:45:08,789:INFO:Initializing Linear Discriminant Analysis
2025-03-29 15:45:08,789:INFO:Total runtime is 65.82237892548243 minutes
2025-03-29 15:45:08,797:INFO:SubProcess create_model() called ==================================
2025-03-29 15:45:08,807:INFO:Initializing create_model()
2025-03-29 15:45:08,807:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 15:45:08,807:INFO:Checking exceptions
2025-03-29 15:45:08,807:INFO:Importing libraries
2025-03-29 15:45:08,807:INFO:Copying training dataset
2025-03-29 15:45:10,207:INFO:Defining folds
2025-03-29 15:45:10,208:INFO:Declaring metric variables
2025-03-29 15:45:10,219:INFO:Importing untrained model
2025-03-29 15:45:10,229:INFO:Linear Discriminant Analysis Imported successfully
2025-03-29 15:45:10,252:INFO:Starting cross validation
2025-03-29 15:45:10,385:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 15:46:13,816:INFO:Calculating mean and std
2025-03-29 15:46:13,934:INFO:Creating metrics dataframe
2025-03-29 15:46:14,017:INFO:Uploading results into container
2025-03-29 15:46:14,030:INFO:Uploading model into container now
2025-03-29 15:46:14,046:INFO:_master_model_container: 11
2025-03-29 15:46:14,046:INFO:_display_container: 2
2025-03-29 15:46:14,062:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2025-03-29 15:46:14,064:INFO:create_model() successfully completed......................................
2025-03-29 15:46:17,494:INFO:SubProcess create_model() end ==================================
2025-03-29 15:46:17,494:INFO:Creating metrics dataframe
2025-03-29 15:46:17,538:INFO:Initializing Extra Trees Classifier
2025-03-29 15:46:17,538:INFO:Total runtime is 66.96819145282109 minutes
2025-03-29 15:46:17,553:INFO:SubProcess create_model() called ==================================
2025-03-29 15:46:17,554:INFO:Initializing create_model()
2025-03-29 15:46:17,555:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 15:46:17,555:INFO:Checking exceptions
2025-03-29 15:46:17,555:INFO:Importing libraries
2025-03-29 15:46:17,555:INFO:Copying training dataset
2025-03-29 15:46:18,603:INFO:Defining folds
2025-03-29 15:46:18,603:INFO:Declaring metric variables
2025-03-29 15:46:18,618:INFO:Importing untrained model
2025-03-29 15:46:18,624:INFO:Extra Trees Classifier Imported successfully
2025-03-29 15:46:18,635:INFO:Starting cross validation
2025-03-29 15:46:18,730:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 15:46:34,390:INFO:Calculating mean and std
2025-03-29 15:46:34,393:INFO:Creating metrics dataframe
2025-03-29 15:46:34,397:INFO:Uploading results into container
2025-03-29 15:46:34,399:INFO:Uploading model into container now
2025-03-29 15:46:34,399:INFO:_master_model_container: 12
2025-03-29 15:46:34,399:INFO:_display_container: 2
2025-03-29 15:46:34,399:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False)
2025-03-29 15:46:34,399:INFO:create_model() successfully completed......................................
2025-03-29 15:46:35,043:INFO:SubProcess create_model() end ==================================
2025-03-29 15:46:35,048:INFO:Creating metrics dataframe
2025-03-29 15:46:35,070:INFO:Initializing Extreme Gradient Boosting
2025-03-29 15:46:35,071:INFO:Total runtime is 67.26040125687916 minutes
2025-03-29 15:46:35,076:INFO:SubProcess create_model() called ==================================
2025-03-29 15:46:35,076:INFO:Initializing create_model()
2025-03-29 15:46:35,076:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000014ACAEC6CA0>, estimator=xgboost, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000014AC9C6E340>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 15:46:35,076:INFO:Checking exceptions
2025-03-29 15:46:35,076:INFO:Importing libraries
2025-03-29 15:46:35,077:INFO:Copying training dataset
2025-03-29 15:46:35,447:INFO:Defining folds
2025-03-29 15:46:35,447:INFO:Declaring metric variables
2025-03-29 15:46:35,452:INFO:Importing untrained model
2025-03-29 15:46:35,457:INFO:Extreme Gradient Boosting Imported successfully
2025-03-29 15:46:35,468:INFO:Starting cross validation
2025-03-29 15:46:35,552:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=1
2025-03-29 16:10:26,791:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 16:10:26,793:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 16:10:26,793:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 16:10:26,793:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-03-29 16:11:04,809:INFO:PyCaret ClassificationExperiment
2025-03-29 16:11:04,829:INFO:Logging name: clf-default-name
2025-03-29 16:11:04,829:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2025-03-29 16:11:04,832:INFO:version 3.2.0
2025-03-29 16:11:04,832:INFO:Initializing setup()
2025-03-29 16:11:04,832:INFO:self.USI: 3660
2025-03-29 16:11:04,834:INFO:self._variable_keys: {'n_jobs_param', 'y', 'y_test', 'fold_groups_param', 'target_param', 'fix_imbalance', 'html_param', 'gpu_n_jobs_param', 'data', 'exp_name_log', 'X_train', 'USI', 'idx', 'X', 'log_plots_param', 'memory', 'seed', 'gpu_param', 'X_test', '_ml_usecase', 'fold_shuffle_param', 'exp_id', 'y_train', '_available_plots', 'fold_generator', 'pipeline', 'logging_param', 'is_multiclass'}
2025-03-29 16:11:04,836:INFO:Checking environment
2025-03-29 16:11:04,836:INFO:python_version: 3.8.18
2025-03-29 16:11:04,838:INFO:python_build: ('default', 'Sep 11 2023 13:39:12')
2025-03-29 16:11:04,838:INFO:machine: AMD64
2025-03-29 16:11:04,841:INFO:platform: Windows-10-10.0.26100-SP0
2025-03-29 16:11:04,859:INFO:Memory: svmem(total=8299257856, available=303198208, percent=96.3, used=7996059648, free=303198208)
2025-03-29 16:11:04,863:INFO:Physical Core: 4
2025-03-29 16:11:04,863:INFO:Logical Core: 8
2025-03-29 16:11:04,866:INFO:Checking libraries
2025-03-29 16:11:04,866:INFO:System:
2025-03-29 16:11:04,866:INFO:    python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
2025-03-29 16:11:04,866:INFO:executable: C:\Users\babig\anaconda3\envs\pycaret_light\python.exe
2025-03-29 16:11:04,866:INFO:   machine: Windows-10-10.0.26100-SP0
2025-03-29 16:11:04,866:INFO:PyCaret required dependencies:
2025-03-29 16:11:09,728:INFO:                 pip: 23.3.1
2025-03-29 16:11:09,729:INFO:          setuptools: 68.2.2
2025-03-29 16:11:09,729:INFO:             pycaret: 3.2.0
2025-03-29 16:11:09,729:INFO:             IPython: 8.12.3
2025-03-29 16:11:09,730:INFO:          ipywidgets: 8.1.1
2025-03-29 16:11:09,730:INFO:                tqdm: 4.66.1
2025-03-29 16:11:09,730:INFO:               numpy: 1.24.4
2025-03-29 16:11:09,730:INFO:              pandas: 1.5.3
2025-03-29 16:11:09,730:INFO:              jinja2: 3.1.3
2025-03-29 16:11:09,730:INFO:               scipy: 1.10.1
2025-03-29 16:11:09,730:INFO:              joblib: 1.3.2
2025-03-29 16:11:09,731:INFO:             sklearn: 1.2.2
2025-03-29 16:11:09,731:INFO:                pyod: 1.1.2
2025-03-29 16:11:09,731:INFO:            imblearn: 0.12.0
2025-03-29 16:11:09,731:INFO:   category_encoders: 2.6.3
2025-03-29 16:11:09,731:INFO:            lightgbm: 4.3.0
2025-03-29 16:11:09,731:INFO:               numba: 0.58.1
2025-03-29 16:11:09,731:INFO:            requests: 2.31.0
2025-03-29 16:11:09,731:INFO:          matplotlib: 3.6.0
2025-03-29 16:11:09,731:INFO:          scikitplot: 0.3.7
2025-03-29 16:11:09,731:INFO:         yellowbrick: 1.5
2025-03-29 16:11:09,731:INFO:              plotly: 5.18.0
2025-03-29 16:11:09,731:INFO:    plotly-resampler: Not installed
2025-03-29 16:11:09,731:INFO:             kaleido: 0.2.1
2025-03-29 16:11:09,732:INFO:           schemdraw: 0.15
2025-03-29 16:11:09,732:INFO:         statsmodels: 0.14.1
2025-03-29 16:11:09,732:INFO:              sktime: 0.21.1
2025-03-29 16:11:09,732:INFO:               tbats: 1.1.3
2025-03-29 16:11:09,732:INFO:            pmdarima: 2.0.4
2025-03-29 16:11:09,732:INFO:              psutil: 5.9.8
2025-03-29 16:11:09,732:INFO:          markupsafe: 2.1.4
2025-03-29 16:11:09,732:INFO:             pickle5: Not installed
2025-03-29 16:11:09,732:INFO:         cloudpickle: 2.2.1
2025-03-29 16:11:09,732:INFO:         deprecation: 2.1.0
2025-03-29 16:11:09,732:INFO:              xxhash: 3.4.1
2025-03-29 16:11:09,732:INFO:           wurlitzer: Not installed
2025-03-29 16:11:09,733:INFO:PyCaret optional dependencies:
2025-03-29 16:11:15,637:INFO:                shap: 0.44.1
2025-03-29 16:11:15,637:INFO:           interpret: 0.5.0
2025-03-29 16:11:15,637:INFO:                umap: 0.5.5
2025-03-29 16:11:15,637:INFO:     ydata_profiling: 4.6.0
2025-03-29 16:11:15,637:INFO:  explainerdashboard: 0.4.5
2025-03-29 16:11:15,637:INFO:             autoviz: Not installed
2025-03-29 16:11:15,637:INFO:           fairlearn: 0.7.0
2025-03-29 16:11:15,637:INFO:          deepchecks: Not installed
2025-03-29 16:11:15,637:INFO:             xgboost: 2.0.3
2025-03-29 16:11:15,637:INFO:            catboost: 1.2.2
2025-03-29 16:11:15,637:INFO:              kmodes: 0.12.2
2025-03-29 16:11:15,637:INFO:             mlxtend: 0.23.1
2025-03-29 16:11:15,637:INFO:       statsforecast: 1.5.0
2025-03-29 16:11:15,637:INFO:        tune_sklearn: 0.5.0
2025-03-29 16:11:15,637:INFO:                 ray: 2.9.1
2025-03-29 16:11:15,637:INFO:            hyperopt: 0.2.7
2025-03-29 16:11:15,637:INFO:              optuna: 3.5.0
2025-03-29 16:11:15,637:INFO:               skopt: 0.9.0
2025-03-29 16:11:15,637:INFO:              mlflow: 1.30.1
2025-03-29 16:11:15,637:INFO:              gradio: 3.50.2
2025-03-29 16:11:15,637:INFO:             fastapi: 0.109.0
2025-03-29 16:11:15,637:INFO:             uvicorn: 0.27.0.post1
2025-03-29 16:11:15,637:INFO:              m2cgen: 0.10.0
2025-03-29 16:11:15,637:INFO:           evidently: 0.2.8
2025-03-29 16:11:15,637:INFO:               fugue: 0.8.6
2025-03-29 16:11:15,637:INFO:           streamlit: Not installed
2025-03-29 16:11:15,637:INFO:             prophet: Not installed
2025-03-29 16:11:15,637:INFO:None
2025-03-29 16:11:15,637:INFO:Set up data.
2025-03-29 16:11:26,758:INFO:Set up folding strategy.
2025-03-29 16:11:26,762:INFO:Set up train/test split.
2025-03-29 16:11:27,716:INFO:Set up index.
2025-03-29 16:11:27,745:INFO:Assigning column types.
2025-03-29 16:11:28,302:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2025-03-29 16:11:28,384:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-03-29 16:11:28,393:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-03-29 16:11:28,462:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 16:11:28,466:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 16:11:28,773:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-03-29 16:11:28,775:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-03-29 16:11:28,819:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 16:11:28,819:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 16:11:28,819:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2025-03-29 16:11:28,900:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-03-29 16:11:28,945:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 16:11:28,949:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 16:11:29,038:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-03-29 16:11:29,093:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 16:11:29,093:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 16:11:29,098:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2025-03-29 16:11:29,238:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 16:11:29,244:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 16:11:29,398:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 16:11:29,405:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 16:11:29,413:INFO:Preparing preprocessing pipeline...
2025-03-29 16:11:29,484:INFO:Set up simple imputation.
2025-03-29 16:11:31,511:INFO:Finished creating preprocessing pipeline.
2025-03-29 16:11:31,737:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\babig\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['Basic_Demos_Enroll_Year',
                                             'Basic_Demos_Study_Site',
                                             'PreInt_Demos_Fam_Child_Ethnicity',
                                             'PreInt_Demos_Fam_Child_Race',
                                             'MRI_Track_Scan_Location',
                                             'Barratt_Barratt_P1_Edu',
                                             'Barratt_Barratt_P1_Occ',
                                             'Barratt_Ba...
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecated'))),
                ('categorical_imputer',
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated')))],
         verbose=False)
2025-03-29 16:11:31,737:INFO:Creating final display dataframe.
2025-03-29 16:11:37,118:INFO:Setup _display_container:                     Description             Value
0                    Session id                42
1                        Target             Sex_F
2                   Target type            Binary
3           Original data shape      (970, 19929)
4        Transformed data shape      (970, 19929)
5   Transformed train set shape      (679, 19929)
6    Transformed test set shape      (291, 19929)
7              Numeric features             19928
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                 5
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              3660
2025-03-29 16:11:37,339:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 16:11:37,344:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 16:11:37,514:INFO:Soft dependency imported: xgboost: 2.0.3
2025-03-29 16:11:37,521:INFO:Soft dependency imported: catboost: 1.2.2
2025-03-29 16:11:37,532:INFO:setup() successfully completed in 32.83s...............
2025-03-29 16:11:42,262:INFO:Initializing compare_models()
2025-03-29 16:11:42,262:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2025-03-29 16:11:42,264:INFO:Checking exceptions
2025-03-29 16:11:42,638:INFO:Preparing display monitor
2025-03-29 16:11:42,849:INFO:Initializing Logistic Regression
2025-03-29 16:11:42,850:INFO:Total runtime is 1.6828378041585285e-05 minutes
2025-03-29 16:11:42,861:INFO:SubProcess create_model() called ==================================
2025-03-29 16:11:42,863:INFO:Initializing create_model()
2025-03-29 16:11:42,863:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:11:42,863:INFO:Checking exceptions
2025-03-29 16:11:42,863:INFO:Importing libraries
2025-03-29 16:11:42,863:INFO:Copying training dataset
2025-03-29 16:11:43,646:INFO:Defining folds
2025-03-29 16:11:43,646:INFO:Declaring metric variables
2025-03-29 16:11:43,646:INFO:Importing untrained model
2025-03-29 16:11:43,663:INFO:Logistic Regression Imported successfully
2025-03-29 16:11:43,683:INFO:Starting cross validation
2025-03-29 16:11:43,851:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:13:37,542:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-03-29 16:13:38,477:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-03-29 16:13:38,927:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-03-29 16:13:39,459:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-03-29 16:13:39,530:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-03-29 16:13:43,287:INFO:Calculating mean and std
2025-03-29 16:13:43,460:INFO:Creating metrics dataframe
2025-03-29 16:13:43,749:INFO:Uploading results into container
2025-03-29 16:13:43,767:INFO:Uploading model into container now
2025-03-29 16:13:43,789:INFO:_master_model_container: 1
2025-03-29 16:13:43,789:INFO:_display_container: 2
2025-03-29 16:13:43,809:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2025-03-29 16:13:43,809:INFO:create_model() successfully completed......................................
2025-03-29 16:13:46,270:INFO:SubProcess create_model() end ==================================
2025-03-29 16:13:46,270:INFO:Creating metrics dataframe
2025-03-29 16:13:46,322:INFO:Initializing K Neighbors Classifier
2025-03-29 16:13:46,322:INFO:Total runtime is 2.0578874468803408 minutes
2025-03-29 16:13:46,342:INFO:SubProcess create_model() called ==================================
2025-03-29 16:13:46,344:INFO:Initializing create_model()
2025-03-29 16:13:46,344:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:13:46,344:INFO:Checking exceptions
2025-03-29 16:13:46,344:INFO:Importing libraries
2025-03-29 16:13:46,346:INFO:Copying training dataset
2025-03-29 16:13:47,654:INFO:Defining folds
2025-03-29 16:13:47,654:INFO:Declaring metric variables
2025-03-29 16:13:47,674:INFO:Importing untrained model
2025-03-29 16:13:47,688:INFO:K Neighbors Classifier Imported successfully
2025-03-29 16:13:47,713:INFO:Starting cross validation
2025-03-29 16:13:47,855:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:14:17,264:INFO:Calculating mean and std
2025-03-29 16:14:17,299:INFO:Creating metrics dataframe
2025-03-29 16:14:17,416:INFO:Uploading results into container
2025-03-29 16:14:17,431:INFO:Uploading model into container now
2025-03-29 16:14:17,440:INFO:_master_model_container: 2
2025-03-29 16:14:17,440:INFO:_display_container: 2
2025-03-29 16:14:17,447:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2025-03-29 16:14:17,447:INFO:create_model() successfully completed......................................
2025-03-29 16:14:19,655:INFO:SubProcess create_model() end ==================================
2025-03-29 16:14:19,655:INFO:Creating metrics dataframe
2025-03-29 16:14:19,688:INFO:Initializing Naive Bayes
2025-03-29 16:14:19,688:INFO:Total runtime is 2.6139939824740095 minutes
2025-03-29 16:14:19,704:INFO:SubProcess create_model() called ==================================
2025-03-29 16:14:19,706:INFO:Initializing create_model()
2025-03-29 16:14:19,706:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:14:19,706:INFO:Checking exceptions
2025-03-29 16:14:19,706:INFO:Importing libraries
2025-03-29 16:14:19,710:INFO:Copying training dataset
2025-03-29 16:14:20,837:INFO:Defining folds
2025-03-29 16:14:20,838:INFO:Declaring metric variables
2025-03-29 16:14:20,854:INFO:Importing untrained model
2025-03-29 16:14:20,868:INFO:Naive Bayes Imported successfully
2025-03-29 16:14:20,890:INFO:Starting cross validation
2025-03-29 16:14:21,157:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:14:37,319:INFO:Calculating mean and std
2025-03-29 16:14:37,369:INFO:Creating metrics dataframe
2025-03-29 16:14:37,460:INFO:Uploading results into container
2025-03-29 16:14:37,465:INFO:Uploading model into container now
2025-03-29 16:14:37,480:INFO:_master_model_container: 3
2025-03-29 16:14:37,480:INFO:_display_container: 2
2025-03-29 16:14:37,489:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2025-03-29 16:14:37,489:INFO:create_model() successfully completed......................................
2025-03-29 16:14:39,320:INFO:SubProcess create_model() end ==================================
2025-03-29 16:14:39,320:INFO:Creating metrics dataframe
2025-03-29 16:14:39,358:INFO:Initializing Decision Tree Classifier
2025-03-29 16:14:39,358:INFO:Total runtime is 2.941816381613414 minutes
2025-03-29 16:14:39,368:INFO:SubProcess create_model() called ==================================
2025-03-29 16:14:39,368:INFO:Initializing create_model()
2025-03-29 16:14:39,368:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:14:39,368:INFO:Checking exceptions
2025-03-29 16:14:39,368:INFO:Importing libraries
2025-03-29 16:14:39,368:INFO:Copying training dataset
2025-03-29 16:14:40,245:INFO:Defining folds
2025-03-29 16:14:40,245:INFO:Declaring metric variables
2025-03-29 16:14:40,253:INFO:Importing untrained model
2025-03-29 16:14:40,261:INFO:Decision Tree Classifier Imported successfully
2025-03-29 16:14:40,272:INFO:Starting cross validation
2025-03-29 16:14:40,621:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:15:23,400:INFO:Calculating mean and std
2025-03-29 16:15:23,429:INFO:Creating metrics dataframe
2025-03-29 16:15:23,517:INFO:Uploading results into container
2025-03-29 16:15:23,529:INFO:Uploading model into container now
2025-03-29 16:15:23,532:INFO:_master_model_container: 4
2025-03-29 16:15:23,532:INFO:_display_container: 2
2025-03-29 16:15:23,537:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=42, splitter='best')
2025-03-29 16:15:23,537:INFO:create_model() successfully completed......................................
2025-03-29 16:15:25,168:INFO:SubProcess create_model() end ==================================
2025-03-29 16:15:25,168:INFO:Creating metrics dataframe
2025-03-29 16:15:25,200:INFO:Initializing SVM - Linear Kernel
2025-03-29 16:15:25,200:INFO:Total runtime is 3.705845284461976 minutes
2025-03-29 16:15:25,210:INFO:SubProcess create_model() called ==================================
2025-03-29 16:15:25,210:INFO:Initializing create_model()
2025-03-29 16:15:25,210:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:15:25,210:INFO:Checking exceptions
2025-03-29 16:15:25,210:INFO:Importing libraries
2025-03-29 16:15:25,210:INFO:Copying training dataset
2025-03-29 16:15:25,801:INFO:Defining folds
2025-03-29 16:15:25,801:INFO:Declaring metric variables
2025-03-29 16:15:25,805:INFO:Importing untrained model
2025-03-29 16:15:25,811:INFO:SVM - Linear Kernel Imported successfully
2025-03-29 16:15:25,822:INFO:Starting cross validation
2025-03-29 16:15:25,904:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:15:34,524:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-03-29 16:15:34,566:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-03-29 16:15:34,831:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-03-29 16:15:36,289:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-03-29 16:15:36,325:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-03-29 16:15:36,916:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-03-29 16:15:36,942:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2025-03-29 16:15:36,963:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-03-29 16:15:37,263:INFO:Calculating mean and std
2025-03-29 16:15:37,268:INFO:Creating metrics dataframe
2025-03-29 16:15:37,278:INFO:Uploading results into container
2025-03-29 16:15:37,278:INFO:Uploading model into container now
2025-03-29 16:15:37,280:INFO:_master_model_container: 5
2025-03-29 16:15:37,280:INFO:_display_container: 2
2025-03-29 16:15:37,282:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2025-03-29 16:15:37,282:INFO:create_model() successfully completed......................................
2025-03-29 16:15:37,528:INFO:SubProcess create_model() end ==================================
2025-03-29 16:15:37,528:INFO:Creating metrics dataframe
2025-03-29 16:15:37,550:INFO:Initializing Ridge Classifier
2025-03-29 16:15:37,550:INFO:Total runtime is 3.911683106422425 minutes
2025-03-29 16:15:37,560:INFO:SubProcess create_model() called ==================================
2025-03-29 16:15:37,560:INFO:Initializing create_model()
2025-03-29 16:15:37,560:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:15:37,560:INFO:Checking exceptions
2025-03-29 16:15:37,560:INFO:Importing libraries
2025-03-29 16:15:37,560:INFO:Copying training dataset
2025-03-29 16:15:37,977:INFO:Defining folds
2025-03-29 16:15:37,977:INFO:Declaring metric variables
2025-03-29 16:15:37,984:INFO:Importing untrained model
2025-03-29 16:15:37,992:INFO:Ridge Classifier Imported successfully
2025-03-29 16:15:38,008:INFO:Starting cross validation
2025-03-29 16:15:38,105:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:15:45,172:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-03-29 16:15:45,391:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-03-29 16:15:45,538:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-03-29 16:15:45,582:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-03-29 16:15:45,621:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\metrics.py", line 182, in _score
    return super()._score(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2025-03-29 16:15:45,942:INFO:Calculating mean and std
2025-03-29 16:15:45,944:INFO:Creating metrics dataframe
2025-03-29 16:15:45,956:INFO:Uploading results into container
2025-03-29 16:15:45,956:INFO:Uploading model into container now
2025-03-29 16:15:45,960:INFO:_master_model_container: 6
2025-03-29 16:15:45,960:INFO:_display_container: 2
2025-03-29 16:15:45,960:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=42, solver='auto',
                tol=0.0001)
2025-03-29 16:15:45,960:INFO:create_model() successfully completed......................................
2025-03-29 16:15:46,286:INFO:SubProcess create_model() end ==================================
2025-03-29 16:15:46,286:INFO:Creating metrics dataframe
2025-03-29 16:15:46,313:INFO:Initializing Random Forest Classifier
2025-03-29 16:15:46,313:INFO:Total runtime is 4.057744232813518 minutes
2025-03-29 16:15:46,327:INFO:SubProcess create_model() called ==================================
2025-03-29 16:15:46,327:INFO:Initializing create_model()
2025-03-29 16:15:46,327:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:15:46,327:INFO:Checking exceptions
2025-03-29 16:15:46,327:INFO:Importing libraries
2025-03-29 16:15:46,327:INFO:Copying training dataset
2025-03-29 16:15:46,890:INFO:Defining folds
2025-03-29 16:15:46,890:INFO:Declaring metric variables
2025-03-29 16:15:46,904:INFO:Importing untrained model
2025-03-29 16:15:46,912:INFO:Random Forest Classifier Imported successfully
2025-03-29 16:15:46,931:INFO:Starting cross validation
2025-03-29 16:15:47,083:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:16:12,057:INFO:Calculating mean and std
2025-03-29 16:16:12,062:INFO:Creating metrics dataframe
2025-03-29 16:16:12,073:INFO:Uploading results into container
2025-03-29 16:16:12,073:INFO:Uploading model into container now
2025-03-29 16:16:12,073:INFO:_master_model_container: 7
2025-03-29 16:16:12,073:INFO:_display_container: 2
2025-03-29 16:16:12,073:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2025-03-29 16:16:12,073:INFO:create_model() successfully completed......................................
2025-03-29 16:16:12,383:INFO:SubProcess create_model() end ==================================
2025-03-29 16:16:12,383:INFO:Creating metrics dataframe
2025-03-29 16:16:12,415:INFO:Initializing Quadratic Discriminant Analysis
2025-03-29 16:16:12,415:INFO:Total runtime is 4.49276341199875 minutes
2025-03-29 16:16:12,425:INFO:SubProcess create_model() called ==================================
2025-03-29 16:16:12,426:INFO:Initializing create_model()
2025-03-29 16:16:12,426:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:16:12,426:INFO:Checking exceptions
2025-03-29 16:16:12,426:INFO:Importing libraries
2025-03-29 16:16:12,426:INFO:Copying training dataset
2025-03-29 16:16:12,931:INFO:Defining folds
2025-03-29 16:16:12,931:INFO:Declaring metric variables
2025-03-29 16:16:12,942:INFO:Importing untrained model
2025-03-29 16:16:12,954:INFO:Quadratic Discriminant Analysis Imported successfully
2025-03-29 16:16:12,972:INFO:Starting cross validation
2025-03-29 16:16:13,089:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:16:38,665:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-03-29 16:16:38,747:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-03-29 16:16:38,763:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-03-29 16:16:38,782:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-03-29 16:16:38,789:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-03-29 16:16:49,420:INFO:Calculating mean and std
2025-03-29 16:16:49,553:INFO:Creating metrics dataframe
2025-03-29 16:16:49,738:INFO:Uploading results into container
2025-03-29 16:16:49,746:INFO:Uploading model into container now
2025-03-29 16:16:49,777:INFO:_master_model_container: 8
2025-03-29 16:16:49,777:INFO:_display_container: 2
2025-03-29 16:16:49,805:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2025-03-29 16:16:49,805:INFO:create_model() successfully completed......................................
2025-03-29 16:16:52,148:INFO:SubProcess create_model() end ==================================
2025-03-29 16:16:52,148:INFO:Creating metrics dataframe
2025-03-29 16:16:52,191:INFO:Initializing Ada Boost Classifier
2025-03-29 16:16:52,191:INFO:Total runtime is 5.155699114004772 minutes
2025-03-29 16:16:52,191:INFO:SubProcess create_model() called ==================================
2025-03-29 16:16:52,191:INFO:Initializing create_model()
2025-03-29 16:16:52,191:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:16:52,191:INFO:Checking exceptions
2025-03-29 16:16:52,191:INFO:Importing libraries
2025-03-29 16:16:52,201:INFO:Copying training dataset
2025-03-29 16:16:52,859:INFO:Defining folds
2025-03-29 16:16:52,859:INFO:Declaring metric variables
2025-03-29 16:16:52,859:INFO:Importing untrained model
2025-03-29 16:16:52,870:INFO:Ada Boost Classifier Imported successfully
2025-03-29 16:16:52,881:INFO:Starting cross validation
2025-03-29 16:16:52,984:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:21:41,032:INFO:Calculating mean and std
2025-03-29 16:21:41,136:INFO:Creating metrics dataframe
2025-03-29 16:21:41,312:INFO:Uploading results into container
2025-03-29 16:21:41,323:INFO:Uploading model into container now
2025-03-29 16:21:41,332:INFO:_master_model_container: 9
2025-03-29 16:21:41,332:INFO:_display_container: 2
2025-03-29 16:21:41,349:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=42)
2025-03-29 16:21:41,349:INFO:create_model() successfully completed......................................
2025-03-29 16:21:43,858:INFO:SubProcess create_model() end ==================================
2025-03-29 16:21:43,858:INFO:Creating metrics dataframe
2025-03-29 16:21:43,910:INFO:Initializing Gradient Boosting Classifier
2025-03-29 16:21:43,910:INFO:Total runtime is 10.017689311504366 minutes
2025-03-29 16:21:43,918:INFO:SubProcess create_model() called ==================================
2025-03-29 16:21:43,918:INFO:Initializing create_model()
2025-03-29 16:21:43,918:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:21:43,918:INFO:Checking exceptions
2025-03-29 16:21:43,920:INFO:Importing libraries
2025-03-29 16:21:43,923:INFO:Copying training dataset
2025-03-29 16:21:44,569:INFO:Defining folds
2025-03-29 16:21:44,579:INFO:Declaring metric variables
2025-03-29 16:21:44,585:INFO:Importing untrained model
2025-03-29 16:21:44,589:INFO:Gradient Boosting Classifier Imported successfully
2025-03-29 16:21:44,600:INFO:Starting cross validation
2025-03-29 16:21:44,680:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:45:42,778:INFO:Calculating mean and std
2025-03-29 16:45:42,873:INFO:Creating metrics dataframe
2025-03-29 16:45:43,011:INFO:Uploading results into container
2025-03-29 16:45:43,027:INFO:Uploading model into container now
2025-03-29 16:45:43,042:INFO:_master_model_container: 10
2025-03-29 16:45:43,042:INFO:_display_container: 2
2025-03-29 16:45:43,055:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2025-03-29 16:45:43,055:INFO:create_model() successfully completed......................................
2025-03-29 16:45:45,625:INFO:SubProcess create_model() end ==================================
2025-03-29 16:45:45,627:INFO:Creating metrics dataframe
2025-03-29 16:45:45,689:INFO:Initializing Linear Discriminant Analysis
2025-03-29 16:45:45,689:INFO:Total runtime is 34.04732836882273 minutes
2025-03-29 16:45:45,695:INFO:SubProcess create_model() called ==================================
2025-03-29 16:45:45,695:INFO:Initializing create_model()
2025-03-29 16:45:45,695:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:45:45,695:INFO:Checking exceptions
2025-03-29 16:45:45,695:INFO:Importing libraries
2025-03-29 16:45:45,704:INFO:Copying training dataset
2025-03-29 16:45:46,502:INFO:Defining folds
2025-03-29 16:45:46,502:INFO:Declaring metric variables
2025-03-29 16:45:46,511:INFO:Importing untrained model
2025-03-29 16:45:46,517:INFO:Linear Discriminant Analysis Imported successfully
2025-03-29 16:45:46,528:INFO:Starting cross validation
2025-03-29 16:45:46,611:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:46:39,029:INFO:Calculating mean and std
2025-03-29 16:46:39,125:INFO:Creating metrics dataframe
2025-03-29 16:46:39,280:INFO:Uploading results into container
2025-03-29 16:46:39,291:INFO:Uploading model into container now
2025-03-29 16:46:39,303:INFO:_master_model_container: 11
2025-03-29 16:46:39,303:INFO:_display_container: 2
2025-03-29 16:46:39,310:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2025-03-29 16:46:39,321:INFO:create_model() successfully completed......................................
2025-03-29 16:46:41,816:INFO:SubProcess create_model() end ==================================
2025-03-29 16:46:41,816:INFO:Creating metrics dataframe
2025-03-29 16:46:41,863:INFO:Initializing Extra Trees Classifier
2025-03-29 16:46:41,863:INFO:Total runtime is 34.98357415994008 minutes
2025-03-29 16:46:41,875:INFO:SubProcess create_model() called ==================================
2025-03-29 16:46:41,875:INFO:Initializing create_model()
2025-03-29 16:46:41,877:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:46:41,877:INFO:Checking exceptions
2025-03-29 16:46:41,877:INFO:Importing libraries
2025-03-29 16:46:41,877:INFO:Copying training dataset
2025-03-29 16:46:42,558:INFO:Defining folds
2025-03-29 16:46:42,558:INFO:Declaring metric variables
2025-03-29 16:46:42,562:INFO:Importing untrained model
2025-03-29 16:46:42,571:INFO:Extra Trees Classifier Imported successfully
2025-03-29 16:46:42,578:INFO:Starting cross validation
2025-03-29 16:46:42,665:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:47:05,374:INFO:Calculating mean and std
2025-03-29 16:47:05,380:INFO:Creating metrics dataframe
2025-03-29 16:47:05,391:INFO:Uploading results into container
2025-03-29 16:47:05,398:INFO:Uploading model into container now
2025-03-29 16:47:05,400:INFO:_master_model_container: 12
2025-03-29 16:47:05,400:INFO:_display_container: 2
2025-03-29 16:47:05,404:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False)
2025-03-29 16:47:05,404:INFO:create_model() successfully completed......................................
2025-03-29 16:47:05,710:INFO:SubProcess create_model() end ==================================
2025-03-29 16:47:05,710:INFO:Creating metrics dataframe
2025-03-29 16:47:05,740:INFO:Initializing Extreme Gradient Boosting
2025-03-29 16:47:05,740:INFO:Total runtime is 35.381516031424205 minutes
2025-03-29 16:47:05,747:INFO:SubProcess create_model() called ==================================
2025-03-29 16:47:05,747:INFO:Initializing create_model()
2025-03-29 16:47:05,747:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=xgboost, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:47:05,747:INFO:Checking exceptions
2025-03-29 16:47:05,747:INFO:Importing libraries
2025-03-29 16:47:05,747:INFO:Copying training dataset
2025-03-29 16:47:06,165:INFO:Defining folds
2025-03-29 16:47:06,165:INFO:Declaring metric variables
2025-03-29 16:47:06,177:INFO:Importing untrained model
2025-03-29 16:47:06,184:INFO:Extreme Gradient Boosting Imported successfully
2025-03-29 16:47:06,196:INFO:Starting cross validation
2025-03-29 16:47:06,317:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 16:56:58,156:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
4 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to 0.0.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\sklearn.py", line 1519, in fit
    self._Booster = train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 2050, in update
    _check_call(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [16:48:37] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\common\io.h:232: bad_malloc: Failed to allocate 2527497952 bytes.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\sklearn.py", line 1519, in fit
    self._Booster = train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 2050, in update
    _check_call(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [16:48:19] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\common\io.h:232: bad_malloc: Failed to allocate 1222982400 bytes.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\sklearn.py", line 1519, in fit
    self._Booster = train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 2050, in update
    _check_call(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [16:48:47] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\common\io.h:232: bad_malloc: Failed to allocate 2364450736 bytes.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\sklearn.py", line 1519, in fit
    self._Booster = train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 2050, in update
    _check_call(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [16:48:52] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\common\io.h:232: bad_malloc: Failed to allocate 2364444240 bytes.

  warnings.warn(some_fits_failed_message, FitFailedWarning)

2025-03-29 16:56:58,210:INFO:Calculating mean and std
2025-03-29 16:56:58,311:INFO:Creating metrics dataframe
2025-03-29 16:56:58,522:INFO:Uploading results into container
2025-03-29 16:56:58,540:INFO:Uploading model into container now
2025-03-29 16:56:58,558:INFO:_master_model_container: 13
2025-03-29 16:56:58,558:INFO:_display_container: 2
2025-03-29 16:56:58,589:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cpu', early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, objective='binary:logistic', ...)
2025-03-29 16:56:58,589:INFO:create_model() successfully completed......................................
2025-03-29 16:57:01,368:WARNING:create_model() for XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cpu', early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, objective='binary:logistic', ...) raised an exception or returned all 0.0, trying without fit_kwargs:
2025-03-29 16:57:01,376:WARNING:Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 796, in compare_models
    assert (
AssertionError

2025-03-29 16:57:01,376:INFO:Initializing create_model()
2025-03-29 16:57:01,376:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=xgboost, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 16:57:01,376:INFO:Checking exceptions
2025-03-29 16:57:01,388:INFO:Importing libraries
2025-03-29 16:57:01,388:INFO:Copying training dataset
2025-03-29 16:57:02,148:INFO:Defining folds
2025-03-29 16:57:02,148:INFO:Declaring metric variables
2025-03-29 16:57:02,158:INFO:Importing untrained model
2025-03-29 16:57:02,165:INFO:Extreme Gradient Boosting Imported successfully
2025-03-29 16:57:02,181:INFO:Starting cross validation
2025-03-29 16:57:02,280:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 17:09:28,004:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
4 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to 0.0.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\sklearn.py", line 1519, in fit
    self._Booster = train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 2050, in update
    _check_call(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [17:00:20] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\common\io.h:232: bad_malloc: Failed to allocate 3505884256 bytes.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\sklearn.py", line 1519, in fit
    self._Booster = train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 2050, in update
    _check_call(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [17:01:09] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\common\io.h:232: bad_malloc: Failed to allocate 3016689920 bytes.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\sklearn.py", line 1519, in fit
    self._Booster = train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 2050, in update
    _check_call(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [16:59:36] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\common\io.h:232: bad_malloc: Failed to allocate 1059923280 bytes.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\sklearn.py", line 1519, in fit
    self._Booster = train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 730, in inner_f
    return func(**kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 2050, in update
    _check_call(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\xgboost\core.py", line 282, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [17:00:25] C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\common\io.h:232: bad_malloc: Failed to allocate 2364439136 bytes.

  warnings.warn(some_fits_failed_message, FitFailedWarning)

2025-03-29 17:09:28,051:INFO:Calculating mean and std
2025-03-29 17:09:28,130:INFO:Creating metrics dataframe
2025-03-29 17:09:28,283:INFO:Uploading results into container
2025-03-29 17:09:28,299:INFO:Uploading model into container now
2025-03-29 17:09:28,300:INFO:_master_model_container: 14
2025-03-29 17:09:28,300:INFO:_display_container: 2
2025-03-29 17:09:28,331:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cpu', early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, objective='binary:logistic', ...)
2025-03-29 17:09:28,331:INFO:create_model() successfully completed......................................
2025-03-29 17:09:30,307:ERROR:create_model() for XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cpu', early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, objective='binary:logistic', ...) raised an exception or returned all 0.0:
2025-03-29 17:09:30,307:ERROR:Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 796, in compare_models
    assert (
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 817, in compare_models
    assert (
AssertionError

2025-03-29 17:09:30,307:INFO:Initializing Light Gradient Boosting Machine
2025-03-29 17:09:30,307:INFO:Total runtime is 57.79096417824427 minutes
2025-03-29 17:09:30,316:INFO:SubProcess create_model() called ==================================
2025-03-29 17:09:30,316:INFO:Initializing create_model()
2025-03-29 17:09:30,316:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 17:09:30,316:INFO:Checking exceptions
2025-03-29 17:09:30,316:INFO:Importing libraries
2025-03-29 17:09:30,316:INFO:Copying training dataset
2025-03-29 17:09:30,999:INFO:Defining folds
2025-03-29 17:09:30,999:INFO:Declaring metric variables
2025-03-29 17:09:31,004:INFO:Importing untrained model
2025-03-29 17:09:31,004:INFO:Light Gradient Boosting Machine Imported successfully
2025-03-29 17:09:31,020:INFO:Starting cross validation
2025-03-29 17:09:31,101:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 17:11:29,284:WARNING:create_model() for lightgbm raised an exception or returned all 0.0, trying without fit_kwargs:
2025-03-29 17:11:29,371:WARNING:Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 794, in compare_models
    model, model_fit_time = self._create_model(**create_model_args)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1533, in _create_model
    model, model_fit_time, model_results, _ = self._create_model_with_cv(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1126, in _create_model_with_cv
    scores = cross_validate(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 266, in cross_validate
    results = parallel(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.


2025-03-29 17:11:29,435:INFO:Initializing create_model()
2025-03-29 17:11:29,435:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 17:11:29,436:INFO:Checking exceptions
2025-03-29 17:11:29,438:INFO:Importing libraries
2025-03-29 17:11:29,444:INFO:Copying training dataset
2025-03-29 17:11:31,307:INFO:Defining folds
2025-03-29 17:11:31,307:INFO:Declaring metric variables
2025-03-29 17:11:31,380:INFO:Importing untrained model
2025-03-29 17:11:31,404:INFO:Light Gradient Boosting Machine Imported successfully
2025-03-29 17:11:31,427:INFO:Starting cross validation
2025-03-29 17:11:31,621:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 17:12:47,963:ERROR:create_model() for lightgbm raised an exception or returned all 0.0:
2025-03-29 17:12:47,996:ERROR:Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 794, in compare_models
    model, model_fit_time = self._create_model(**create_model_args)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1533, in _create_model
    model, model_fit_time, model_results, _ = self._create_model_with_cv(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1126, in _create_model_with_cv
    scores = cross_validate(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 266, in cross_validate
    results = parallel(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 815, in compare_models
    model, model_fit_time = self._create_model(**create_model_args)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1533, in _create_model
    model, model_fit_time, model_results, _ = self._create_model_with_cv(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1126, in _create_model_with_cv
    scores = cross_validate(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 266, in cross_validate
    results = parallel(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\utils\parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 736, in get_result
    return self._return_or_raise()
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.


2025-03-29 17:12:48,019:INFO:Initializing CatBoost Classifier
2025-03-29 17:12:48,019:INFO:Total runtime is 61.086172592639926 minutes
2025-03-29 17:12:48,187:INFO:SubProcess create_model() called ==================================
2025-03-29 17:12:48,197:INFO:Initializing create_model()
2025-03-29 17:12:48,197:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=catboost, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 17:12:48,197:INFO:Checking exceptions
2025-03-29 17:12:48,197:INFO:Importing libraries
2025-03-29 17:12:48,200:INFO:Copying training dataset
2025-03-29 17:12:49,154:INFO:Defining folds
2025-03-29 17:12:49,156:INFO:Declaring metric variables
2025-03-29 17:12:49,171:INFO:Importing untrained model
2025-03-29 17:12:49,208:INFO:CatBoost Classifier Imported successfully
2025-03-29 17:12:49,222:INFO:Starting cross validation
2025-03-29 17:12:49,395:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 17:14:02,221:WARNING:create_model() for catboost raised an exception or returned all 0.0, trying without fit_kwargs:
2025-03-29 17:14:02,259:WARNING:Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 794, in compare_models
    model, model_fit_time = self._create_model(**create_model_args)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1533, in _create_model
    model, model_fit_time, model_results, _ = self._create_model_with_cv(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1126, in _create_model_with_cv
    scores = cross_validate(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 285, in cross_validate
    _warn_or_raise_about_fit_failures(results, error_score)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 367, in _warn_or_raise_about_fit_failures
    raise ValueError(all_fits_failed_message)
ValueError: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\catboost\core.py", line 5100, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\catboost\core.py", line 2319, in _fit
    self._train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\catboost\core.py", line 1723, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4645, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4694, in _catboost._CatBoost._train
_catboost.CatBoostError: bad allocation


2025-03-29 17:14:02,315:INFO:Initializing create_model()
2025-03-29 17:14:02,315:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=catboost, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 17:14:02,315:INFO:Checking exceptions
2025-03-29 17:14:02,317:INFO:Importing libraries
2025-03-29 17:14:02,323:INFO:Copying training dataset
2025-03-29 17:14:04,634:INFO:Defining folds
2025-03-29 17:14:04,637:INFO:Declaring metric variables
2025-03-29 17:14:04,781:INFO:Importing untrained model
2025-03-29 17:14:04,815:INFO:CatBoost Classifier Imported successfully
2025-03-29 17:14:04,851:INFO:Starting cross validation
2025-03-29 17:14:05,137:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 17:14:53,840:ERROR:create_model() for catboost raised an exception or returned all 0.0:
2025-03-29 17:14:53,858:ERROR:Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 794, in compare_models
    model, model_fit_time = self._create_model(**create_model_args)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1533, in _create_model
    model, model_fit_time, model_results, _ = self._create_model_with_cv(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1126, in _create_model_with_cv
    scores = cross_validate(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 285, in cross_validate
    _warn_or_raise_about_fit_failures(results, error_score)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 367, in _warn_or_raise_about_fit_failures
    raise ValueError(all_fits_failed_message)
ValueError: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\catboost\core.py", line 5100, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\catboost\core.py", line 2319, in _fit
    self._train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\catboost\core.py", line 1723, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4645, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4694, in _catboost._CatBoost._train
_catboost.CatBoostError: bad allocation


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 815, in compare_models
    model, model_fit_time = self._create_model(**create_model_args)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1533, in _create_model
    model, model_fit_time, model_results, _ = self._create_model_with_cv(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 1126, in _create_model_with_cv
    scores = cross_validate(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 285, in cross_validate
    _warn_or_raise_about_fit_failures(results, error_score)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 367, in _warn_or_raise_about_fit_failures
    raise ValueError(all_fits_failed_message)
ValueError: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 275, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\joblib\memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\pycaret\internal\pipeline.py", line 68, in _fit_one
    transformer.fit(*args, **fit_params)
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\catboost\core.py", line 5100, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\catboost\core.py", line 2319, in _fit
    self._train(
  File "C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\catboost\core.py", line 1723, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4645, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4694, in _catboost._CatBoost._train
_catboost.CatBoostError: bad allocation


2025-03-29 17:14:53,919:INFO:Initializing Dummy Classifier
2025-03-29 17:14:53,919:INFO:Total runtime is 63.18450923760732 minutes
2025-03-29 17:14:54,046:INFO:SubProcess create_model() called ==================================
2025-03-29 17:14:54,058:INFO:Initializing create_model()
2025-03-29 17:14:54,062:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=dummy, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000025851A7AE50>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 17:14:54,062:INFO:Checking exceptions
2025-03-29 17:14:54,062:INFO:Importing libraries
2025-03-29 17:14:54,062:INFO:Copying training dataset
2025-03-29 17:14:55,129:INFO:Defining folds
2025-03-29 17:14:55,129:INFO:Declaring metric variables
2025-03-29 17:14:55,133:INFO:Importing untrained model
2025-03-29 17:14:55,154:INFO:Dummy Classifier Imported successfully
2025-03-29 17:14:55,176:INFO:Starting cross validation
2025-03-29 17:14:55,355:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2025-03-29 17:15:01,763:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-03-29 17:15:02,118:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-03-29 17:15:02,141:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-03-29 17:15:02,160:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-03-29 17:15:02,251:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2025-03-29 17:15:02,455:INFO:Calculating mean and std
2025-03-29 17:15:02,513:INFO:Creating metrics dataframe
2025-03-29 17:15:02,591:INFO:Uploading results into container
2025-03-29 17:15:02,596:INFO:Uploading model into container now
2025-03-29 17:15:02,611:INFO:_master_model_container: 15
2025-03-29 17:15:02,611:INFO:_display_container: 2
2025-03-29 17:15:02,620:INFO:DummyClassifier(constant=None, random_state=42, strategy='prior')
2025-03-29 17:15:02,620:INFO:create_model() successfully completed......................................
2025-03-29 17:15:05,160:INFO:SubProcess create_model() end ==================================
2025-03-29 17:15:05,160:INFO:Creating metrics dataframe
2025-03-29 17:15:05,232:INFO:Initializing create_model()
2025-03-29 17:15:05,232:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000025876B347F0>, estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-03-29 17:15:05,233:INFO:Checking exceptions
2025-03-29 17:15:05,238:INFO:Importing libraries
2025-03-29 17:15:05,238:INFO:Copying training dataset
2025-03-29 17:15:05,633:INFO:Defining folds
2025-03-29 17:15:05,633:INFO:Declaring metric variables
2025-03-29 17:15:05,634:INFO:Importing untrained model
2025-03-29 17:15:05,634:INFO:Declaring custom model
2025-03-29 17:15:05,634:INFO:Logistic Regression Imported successfully
2025-03-29 17:15:05,729:INFO:Cross validation set to False
2025-03-29 17:15:05,729:INFO:Fitting Model
2025-03-29 17:15:32,517:WARNING:C:\Users\babig\anaconda3\envs\pycaret_light\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-03-29 17:15:32,537:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2025-03-29 17:15:32,537:INFO:create_model() successfully completed......................................
2025-03-29 17:15:32,883:INFO:_master_model_container: 15
2025-03-29 17:15:32,883:INFO:_display_container: 2
2025-03-29 17:15:32,883:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2025-03-29 17:15:32,883:INFO:compare_models() successfully completed......................................
